name: artefact
description: Flutter Web Art Gallery
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  animations: ^2.0.11
  artefact_ui:
    path: packages/artefact_ui
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.2
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  flutter_tilt: ^3.2.1
  gap: ^3.0.1
  get_it: ^8.0.3
  glass_kit: ^4.0.1
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  heroine: ^0.4.0
  intl: ^0.19.0
  mesh: ^0.4.2
  model_viewer_plus: ^1.9.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.8.2
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/icons/
    - assets/google_fonts/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/google_fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Lato-Black.ttf
          weight: 900

    - family: PlayfairDisplay
      fonts:
        - asset: assets/google_fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/PlayfairDisplay-Bold.ttf
          weight: 700

  uses-material-design: true
  generate: true

flutter_gen:
  assets:
    enabled: true
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true
